from __future__ import annotations

import gzip
import json
from dataclasses import replace
from pathlib import Path

import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq
import pytest

from protein_distance_diffusion.config import load_yaml
from protein_distance_diffusion.evaluation.e006_geometry_source_audit import (
    AUDIT_SCHEMA_VERSION,
    CANONICALIZATION_POLICY_VERSION,
    CHIRALITY_CONVENTION_VERSION,
    COORDINATE_ANCHOR_POLICY_VERSION,
    TARGET_MAPPING_POLICY_VERSION,
    AuditHeartbeat,
    BackboneResidue,
    analyze_backbone_residues,
    compare_ca_distance_matrix,
    decode_identifier_array,
    eligibility_counts,
    eligibility_manifest_rows,
    enforce_rss_limit,
    enrich_source_locators,
    frame_is_right_handed,
    frame_quality,
    full_corpus_storage_estimates,
    identifier_representation_inventory,
    load_npz_geometry_evidence,
    local_frame,
    native_chirality_signed_volume,
    parquet_schema_inventory,
    parse_backbone_mmcif,
    phase1_authorization,
    project_full_corpus_eligibility,
    pseudo_cb_coordinate,
    publish_audit_outputs,
    reconcile_npz_calpha_anchors,
    residue_geometry_diagnostics,
    resolve_identifier_locator,
    resolve_rich_geometry_eligibility,
    resolve_verified_target_mapping,
    resolve_within_roots,
    scan_stratified_partition,
    select_atom_alternate_locations,
    sha256_file,
    sidecar_storage_estimates,
    stratified_select,
    validate_audit_config,
    write_failed_protocol,
)


def _residue(
    index: int,
    *,
    name: str = "ALA",
    one_letter: str | None = None,
    missing: str | None = None,
    insertion: str = "",
    chirality_class: str | None = None,
) -> BackboneResidue:
    # AlphaFold ideal-residue coordinates are fixed external references, not
    # generated by the pseudo-CB implementation under test.
    origin = np.asarray([index * 3.38, 0.0, 0.0])
    cb = np.asarray([-0.529, -0.774, -1.205])
    if name == "ARG":
        cb = np.asarray([-0.524, -0.778, -1.209])
    atoms = {
        "N": origin + np.asarray([-0.525, 1.363, 0.0]),
        "CA": origin,
        "C": origin + np.asarray([1.526, 0.0, 0.0]),
        "O": origin + np.asarray([2.153, -1.062, 0.0]),
        "CB": origin + cb,
    }
    if missing:
        atoms.pop(missing)
    token = one_letter if one_letter is not None else "G" if name == "GLY" else "A"
    return BackboneResidue(
        name,
        token,
        str(index + 1),
        insertion,
        atoms,
        chirality_class=chirality_class,
    )


def _matrix(residues: list[BackboneResidue]) -> np.ndarray:
    coordinates = np.stack([residue.atoms["CA"] for residue in residues])
    return np.linalg.norm(coordinates[:, None] - coordinates[None, :], axis=-1)


def _write_npz_evidence(
    tmp_path: Path,
    residue_ids: list[str],
    coordinates: np.ndarray,
    *,
    matrix: np.ndarray | None = None,
    residue_mask: np.ndarray | None = None,
    metadata: dict[str, object] | None = None,
):
    path = tmp_path / f"sample-{len(list(tmp_path.glob('sample-*.npz')))}.npz"
    coordinates = np.asarray(coordinates, dtype=np.float32)
    if matrix is None:
        matrix = np.linalg.norm(coordinates[:, None] - coordinates[None, :], axis=-1).astype(np.float32)
    np.savez_compressed(
        path,
        residue_ids=np.asarray(residue_ids),
        ca_coordinates=coordinates,
        residue_mask=(np.ones(len(residue_ids), dtype=np.bool_) if residue_mask is None else np.asarray(residue_mask)),
        distance_matrix=np.asarray(matrix, dtype=np.float32),
        metadata=np.asarray(json.dumps(metadata or {}, sort_keys=True)),
    )
    return load_npz_geometry_evidence(path)


def _with_atom_candidates(
    residue: BackboneResidue,
    candidates: dict[str, list[tuple[str | None, float | None, np.ndarray]]],
) -> BackboneResidue:
    return replace(residue, atom_candidates={name: tuple(values) for name, values in candidates.items()})


def _target_residue(
    index: int,
    *,
    name: str = "ALA",
    one_letter: str | None = None,
    parent: str | None = None,
    missing: str | None = None,
) -> BackboneResidue:
    residue = _residue(index, name=name, one_letter=one_letter, missing=missing)
    return replace(
        residue,
        auth_sequence_id=str(index + 1),
        label_sequence_id=str(index + 1),
        authoritative_parent_comp_id=parent,
        authoritative_parent_source=("_chem_comp.mon_nstd_parent_comp_id" if parent else None),
        chirality_class=("mapped_modified_l" if parent else residue.chirality_class),
    )


def _resolve(residues: list[BackboneResidue], sequence: str) -> dict[str, object]:
    return resolve_verified_target_mapping(
        residues,
        sample_id="synthetic-sample",
        expected_sequence=sequence,
        residue_ids=json.dumps([str(index + 1) for index in range(len(sequence))]),
        insertion_codes=json.dumps([""] * len(sequence)),
        residue_id_convention="auth_seq_id_insertion",
        pairing_canonicalization_version="sequence_geometry_pairing_v1",
    )


@pytest.mark.parametrize(
    "raw_value,representation",
    [
        (["10", "11A"], "native_array"),
        (("10", "11A"), "native_array"),
        (np.asarray(["10", "11A"]), "native_array"),
        (pa.array(["10", "11A"]), "native_array"),
        (pa.scalar(["10", "11A"], type=pa.list_(pa.string())), "native_array"),
        ('["10", "11A"]', "json_array_string"),
        ('  ["10", "11A"] \n', "json_array_string"),
        (b'["10", "11A"]', "utf8_json_bytes"),
    ],
)
def test_typed_identifier_decoder_supported_arrays(raw_value: object, representation: str) -> None:
    decoded = decode_identifier_array(
        sample_id="sample-supported",
        field_name="residue_ids",
        residue_id_convention="auth_seq_id_insertion",
        raw_value=raw_value,
    )
    assert decoded.values == ("10", "11A")
    assert decoded.status == "ok"
    assert decoded.representation == representation
    assert decoded.diagnostic["sample_id"] == "sample-supported"
    assert decoded.diagnostic["field_name"] == "residue_ids"
    assert len(decoded.diagnostic["preview"]) <= 160
    assert len(decoded.diagnostic["raw_sha256"]) == 64


def test_symbolic_identifier_locators_resolve_before_decoding() -> None:
    source_record = {
        "sample_id": "locator-ok",
        "residue_ids": '["10", "11"]',
        "insertion_codes": '["", "A"]',
    }
    residues = [
        replace(_target_residue(0), auth_sequence_id="10", insertion_code=""),
        replace(_target_residue(1), auth_sequence_id="11", insertion_code="A"),
    ]
    mapping = resolve_verified_target_mapping(
        residues,
        sample_id="locator-ok",
        expected_sequence="AA",
        residue_ids="audit:residue_ids",
        insertion_codes="audit:insertion_codes",
        residue_id_convention="auth_seq_id_insertion",
        pairing_canonicalization_version="sequence_geometry_pairing_v1",
        audit_source_record=source_record,
        audit_source_artifact="compact/tables/matrix_pair_alignments",
        direct_source_artifact="pairing/eligible_train.parquet",
    )
    assert mapping["mapping_verified"] is True
    assert mapping["residue_ids_original_locator"] == "audit:residue_ids"
    assert mapping["residue_ids_resolved_field_name"] == "residue_ids"
    assert mapping["residue_ids_source_record_key"] == "locator-ok"
    assert mapping["residue_ids_locator_resolution_status"] == "resolved"
    assert mapping["residue_ids_decoder_status"] == "ok"
    assert mapping["residue_ids_decoded_identifier_count"] == 2
    assert len(mapping["residue_ids_resolved_payload_sha256"]) == 64
    assert mapping["insertion_codes_decoded_identifier_count"] == 2
    diagnostics = json.loads(mapping["identifier_decode_diagnostics_json"])
    assert all(item["locator_resolution_status"] == "resolved" for item in diagnostics)


def test_compact_audit_payload_is_retained_separately_from_pairing_locator(tmp_path: Path) -> None:
    processed = tmp_path / "processed.parquet"
    pq.write_table(pa.Table.from_pylist([{"sample_id": "sample-a", "model_number": 1}]), processed)
    alignment = tmp_path / "audit" / "tables" / "matrix_pair_alignments"
    alignment.mkdir(parents=True)
    pq.write_table(
        pa.Table.from_pylist(
            [
                {
                    "sample_id": "sample-a",
                    "residue_ids": '["1"]',
                    "insertion_codes": '[""]',
                }
            ]
        ),
        alignment / "part-000000.parquet",
    )
    [enriched] = enrich_source_locators(
        [
            {
                "sample_id": "sample-a",
                "residue_ids": "audit:residue_ids",
                "insertion_codes": "audit:insertion_codes",
            }
        ],
        processed_manifest=processed,
        audit_provenance=tmp_path / "audit",
    )
    assert enriched["residue_ids"] == "audit:residue_ids"
    assert enriched["_identifier_audit_source_record"]["residue_ids"] == '["1"]'
    assert enriched["_identifier_audit_source_record"]["insertion_codes"] == '[""]'


@pytest.mark.parametrize(
    "source_record,expected_status",
    [
        (None, "referenced_record_unavailable"),
        ({"sample_id": "missing-field", "insertion_codes": '[""]'}, "referenced_field_unavailable"),
    ],
)
def test_unresolved_identifier_locator_is_a_distinct_resolved_exclusion(
    source_record: dict[str, object] | None, expected_status: str
) -> None:
    mapping = resolve_verified_target_mapping(
        [_target_residue(0)],
        sample_id="missing-field",
        expected_sequence="A",
        residue_ids="audit:residue_ids",
        insertion_codes="audit:insertion_codes",
        residue_id_convention="auth_seq_id_insertion",
        pairing_canonicalization_version="sequence_geometry_pairing_v1",
        audit_source_record=source_record,
    )
    decision = resolve_rich_geometry_eligibility(mapping, {})
    assert mapping["residue_ids_locator_resolution_status"] == expected_status
    assert mapping["residue_ids_decoder_status"] == "not_run_locator_unavailable"
    assert decision["exclusion_reason"] == "excluded_identifier_locator_unavailable"
    assert decision["resolved_exclusion_count"] == 1


def test_malformed_resolved_locator_payload_retains_serialization_exclusion() -> None:
    mapping = resolve_verified_target_mapping(
        [_target_residue(0)],
        sample_id="resolved-malformed",
        expected_sequence="A",
        residue_ids="audit:residue_ids",
        insertion_codes="audit:insertion_codes",
        residue_id_convention="auth_seq_id_insertion",
        pairing_canonicalization_version="sequence_geometry_pairing_v1",
        audit_source_record={"residue_ids": "not-json", "insertion_codes": '[""]'},
    )
    assert mapping["residue_ids_locator_resolution_status"] == "resolved"
    assert mapping["residue_ids_decoder_status"] == "malformed"
    assert resolve_rich_geometry_eligibility(mapping, {})["exclusion_reason"] == (
        "excluded_invalid_residue_id_serialization"
    )


def test_locator_arrays_must_have_compatible_lengths_and_preserve_blanks() -> None:
    common = {
        "source_residues": [_target_residue(0), _target_residue(1)],
        "sample_id": "locator-lengths",
        "expected_sequence": "AA",
        "residue_ids": "audit:residue_ids",
        "insertion_codes": "audit:insertion_codes",
        "residue_id_convention": "auth_seq_id_insertion",
        "pairing_canonicalization_version": "sequence_geometry_pairing_v1",
    }
    incompatible = resolve_verified_target_mapping(
        **common,
        audit_source_record={"residue_ids": '["1", "2"]', "insertion_codes": '[""]'},
    )
    assert resolve_rich_geometry_eligibility(incompatible, {})["exclusion_reason"] == (
        "excluded_residue_id_namespace_contradiction"
    )
    compatible = resolve_verified_target_mapping(
        **common,
        audit_source_record={"residue_ids": '["1", "2"]', "insertion_codes": '["", ""]'},
    )
    assert compatible["mapping_verified"] is True
    insertion_diagnostic = json.loads(compatible["identifier_decode_diagnostics_json"])[1]
    assert insertion_diagnostic["decoded_count"] == 2


@pytest.mark.parametrize(
    "convention,identifiers,residues",
    [
        (
            "auth_seq_id_insertion",
            '["20", "21"]',
            [
                replace(_target_residue(0), auth_sequence_id="20"),
                replace(_target_residue(1), auth_sequence_id="21"),
            ],
        ),
        ("position_zero_based", '["0", "1"]', [_target_residue(0), _target_residue(1)]),
    ],
)
def test_locator_resolution_honors_selected_identifier_convention(
    convention: str, identifiers: str, residues: list[BackboneResidue]
) -> None:
    mapping = resolve_verified_target_mapping(
        residues,
        sample_id=f"locator-{convention}",
        expected_sequence="AA",
        residue_ids="audit:residue_ids",
        insertion_codes="audit:insertion_codes",
        residue_id_convention=convention,
        pairing_canonicalization_version="sequence_geometry_pairing_v1",
        audit_source_record={"residue_ids": identifiers, "insertion_codes": '["", ""]'},
    )
    assert mapping["mapping_verified"] is True
    assert mapping["residue_id_convention"] == convention


def test_payload_decoder_never_accepts_symbolic_locator() -> None:
    resolution = resolve_identifier_locator(
        sample_id="hard-invariant",
        field_name="residue_ids",
        raw_value="audit:residue_ids",
        audit_source_record=None,
        audit_source_artifact="audit",
        direct_source_artifact="pairing",
    )
    assert resolution.status == "referenced_record_unavailable"
    with pytest.raises(ValueError, match="identifier_locator_reached_payload_decoder"):
        decode_identifier_array(
            sample_id="hard-invariant",
            field_name="residue_ids",
            residue_id_convention="auth_seq_id_insertion",
            raw_value="audit:residue_ids",
        )


def test_processing_continues_after_per_sample_locator_failure() -> None:
    outcomes = []
    for sample_id, source_record in (
        ("bad", None),
        ("later-good", {"residue_ids": '["1"]', "insertion_codes": '[""]'}),
    ):
        mapping = resolve_verified_target_mapping(
            [_target_residue(0)],
            sample_id=sample_id,
            expected_sequence="A",
            residue_ids="audit:residue_ids",
            insertion_codes="audit:insertion_codes",
            residue_id_convention="auth_seq_id_insertion",
            pairing_canonicalization_version="sequence_geometry_pairing_v1",
            audit_source_record=source_record,
        )
        outcomes.append(resolve_rich_geometry_eligibility(mapping, {}))
    assert outcomes[0]["exclusion_reason"] == "excluded_identifier_locator_unavailable"
    assert outcomes[1]["rich_geometry_eligible"] is True


@pytest.mark.parametrize("raw_value", [None, "", "   ", "null", "NONE", "NaN", float("nan"), np.float64("nan")])
def test_typed_identifier_decoder_documented_missing_values(raw_value: object) -> None:
    decoded = decode_identifier_array(
        sample_id="sample-missing",
        field_name="residue_ids",
        residue_id_convention="label_seq_id",
        raw_value=raw_value,
    )
    assert decoded.status == "missing"
    assert decoded.representation == "missing"
    assert decoded.values == ()


def test_empty_decoded_identifier_array_is_mapping_unavailable() -> None:
    mapping = resolve_verified_target_mapping(
        [_target_residue(0)],
        sample_id="empty-array",
        expected_sequence="A",
        residue_ids="[]",
        insertion_codes="[]",
        residue_id_convention="auth_seq_id_insertion",
        pairing_canonicalization_version="sequence_geometry_pairing_v1",
    )
    assert resolve_rich_geometry_eligibility(mapping, {})["exclusion_reason"] == (
        "excluded_identity_mapping_unavailable"
    )


@pytest.mark.parametrize("raw_value", ["not-json", b"\xff\xfe", '["1", ["2"]]', '["1", ""]'])
def test_typed_identifier_decoder_rejects_malformed_or_nested_values(raw_value: object) -> None:
    decoded = decode_identifier_array(
        sample_id="sample-malformed",
        field_name="residue_ids",
        residue_id_convention="auth_seq_id_insertion",
        raw_value=raw_value,
    )
    assert decoded.status == "malformed"
    assert decoded.values == ()
    assert decoded.diagnostic["raw_byte_length"] > 0
    assert len(decoded.diagnostic["preview"]) <= 160


@pytest.mark.parametrize("raw_value", ['"scalar"', "123", '{"id": 1}'])
def test_typed_identifier_decoder_rejects_wrong_json_types(raw_value: str) -> None:
    decoded = decode_identifier_array(
        sample_id="sample-wrong-type",
        field_name="residue_ids",
        residue_id_convention="label_seq_id",
        raw_value=raw_value,
    )
    assert decoded.status == "wrong_json_type"
    assert decoded.representation == "wrong_json_type"


def test_identifier_duplicates_are_reported_and_insertion_codes_are_preserved() -> None:
    identifiers = decode_identifier_array(
        sample_id="insertions",
        field_name="residue_ids",
        residue_id_convention="auth_seq_id_insertion",
        raw_value='["10", "10"]',
    )
    insertions = decode_identifier_array(
        sample_id="insertions",
        field_name="insertion_codes",
        residue_id_convention="auth_seq_id_insertion",
        raw_value='["", "A"]',
    )
    assert identifiers.duplicate_identifiers is True
    assert insertions.values == ("", "A")
    residues = [
        replace(_target_residue(0), auth_sequence_id="10", insertion_code=""),
        replace(_target_residue(1), auth_sequence_id="10", insertion_code="A"),
    ]
    mapping = resolve_verified_target_mapping(
        residues,
        sample_id="insertions",
        expected_sequence="AA",
        residue_ids='["10", "10"]',
        insertion_codes='["", "A"]',
        residue_id_convention="auth_seq_id_insertion",
        pairing_canonicalization_version="sequence_geometry_pairing_v1",
    )
    assert mapping["mapping_verified"] is True
    assert mapping["residue_id_duplicate_identifiers"] is True


def test_namespace_fallback_requires_explicit_pairing_provenance() -> None:
    residues = [replace(_target_residue(0), label_sequence_id="7")]
    common = {
        "source_residues": residues,
        "sample_id": "fallback",
        "expected_sequence": "A",
        "residue_ids": None,
        "insertion_codes": '[""]',
        "residue_id_convention": "auth_seq_id_insertion",
        "pairing_canonicalization_version": "sequence_geometry_pairing_v1",
        "alternative_residue_ids": {"label_seq_id": '["7"]'},
    }
    allowed = resolve_verified_target_mapping(
        **common,
        authorized_residue_id_conventions={"label_seq_id"},
    )
    assert allowed["mapping_verified"] is True
    assert allowed["residue_id_fallback_used"] is True
    assert allowed["residue_id_convention"] == "label_seq_id"
    inventory = identifier_representation_inventory([allowed])
    assert inventory["residue_ids"]["missing"] == 1
    assert inventory["residue_ids"]["json_array_string"] == 1

    forbidden = resolve_verified_target_mapping(
        **common,
        authorized_residue_id_conventions=set(),
    )
    decision = resolve_rich_geometry_eligibility(forbidden, {})
    assert forbidden["residue_id_fallback_used"] is False
    assert decision["exclusion_reason"] == "excluded_identity_mapping_unavailable"


def test_malformed_identifier_excludes_only_that_sample_and_inventory_is_bounded() -> None:
    residues = [_target_residue(0)]
    outcomes = []
    for sample_id, raw in (("bad", "not-json"), ("later-good", '["1"]')):
        mapping = resolve_verified_target_mapping(
            residues,
            sample_id=sample_id,
            expected_sequence="A",
            residue_ids=raw,
            insertion_codes='[""]',
            residue_id_convention="auth_seq_id_insertion",
            pairing_canonicalization_version="sequence_geometry_pairing_v1",
        )
        outcomes.append({**mapping, **resolve_rich_geometry_eligibility(mapping, {})})
    assert outcomes[0]["exclusion_reason"] == "excluded_invalid_residue_id_serialization"
    assert outcomes[0]["resolved_exclusion_count"] == 1
    assert outcomes[1]["rich_geometry_eligible"] is True
    diagnostic = json.loads(outcomes[0]["identifier_decode_diagnostics_json"])[0]
    assert diagnostic["sample_id"] == "bad"
    assert diagnostic["field_name"] == "residue_ids"
    assert len(diagnostic["preview"]) <= 160
    inventory = identifier_representation_inventory(outcomes)
    assert inventory["residue_ids"]["malformed"] == 1
    assert inventory["residue_ids"]["json_array_string"] == 1
    assert set(inventory["all_identifier_fields"]) == {
        "native_array",
        "json_array_string",
        "utf8_json_bytes",
        "missing",
        "malformed",
        "wrong_json_type",
        "duplicate_identifiers",
    }


def test_duplicate_effective_namespace_is_resolved_contradiction() -> None:
    mapping = resolve_verified_target_mapping(
        [_target_residue(0), _target_residue(1)],
        sample_id="duplicate-effective",
        expected_sequence="AA",
        residue_ids='["1", "1"]',
        insertion_codes='["", ""]',
        residue_id_convention="auth_seq_id_insertion",
        pairing_canonicalization_version="sequence_geometry_pairing_v1",
    )
    decision = resolve_rich_geometry_eligibility(mapping, {})
    assert "duplicate_effective_residue_identifiers" in mapping["mapping_errors"]
    assert decision["exclusion_reason"] == "excluded_residue_id_namespace_contradiction"


def test_perfect_backbone_frames_torsions_and_glycine_pseudo_cb() -> None:
    residues = [_residue(0, name="GLY", missing="CB"), _residue(1), _residue(2)]
    result = analyze_backbone_residues(residues, expected_sequence="GAA", stored_matrix=_matrix(residues))
    assert result["exact_residue_identity_agreement"] is True
    assert result["complete_local_frame_fraction"] == 1
    assert result["cb_availability_fraction"] == pytest.approx(2 / 3)
    assert result["pseudo_cb_computable_fraction"] == 1
    assert result["phi_computable_fraction"] == pytest.approx(2 / 3)
    assert result["psi_computable_fraction"] == pytest.approx(2 / 3)
    assert result["omega_computable_fraction"] == pytest.approx(2 / 3)
    assert json.loads(result["frame_right_handed_signs_json"]) == [True, True, True]
    assert json.loads(result["local_frame_mask_json"]) == [True, True, True]
    assert json.loads(result["phi_mask_json"]) == [False, True, True]
    assert result["matrix_comparison"]["rmse_angstrom"] == pytest.approx(0)
    pseudo = pseudo_cb_coordinate(residues[0].atoms["N"], residues[0].atoms["CA"], residues[0].atoms["C"])
    assert pseudo.shape == (3,)


@pytest.mark.parametrize("missing", ["N", "C", "O", "CA"])
def test_missing_backbone_atoms_are_explicit(missing: str) -> None:
    complete = [_residue(0), _residue(1)]
    residues = [complete[0], _residue(1, missing=missing)]
    result = analyze_backbone_residues(residues, expected_sequence="AA", stored_matrix=_matrix(complete))
    assert result[f"{missing.lower()}_availability_fraction"] == 0.5
    if missing in {"N", "C", "CA"}:
        assert result["complete_local_frame_fraction"] == 0.5
    if missing == "CA":
        assert "missing_calpha" in result["unavailable_reasons"]


def test_insertion_altloc_chain_break_identity_and_matrix_contradictions() -> None:
    first = _residue(0, insertion="A")
    second = _residue(1)
    broken_atoms = {key: value + np.asarray([20.0, 0.0, 0.0]) for key, value in second.atoms.items()}
    broken = BackboneResidue("ALA", "A", "2", "", broken_atoms, alternate_location_count=2)
    stored = np.zeros((2, 2), dtype=np.float64)
    result = analyze_backbone_residues([first, broken], expected_sequence="AG", stored_matrix=stored)
    assert result["insertion_code_count"] == 1
    assert result["alternate_location_count"] == 2
    assert result["chain_break_count"] == 1
    assert result["exact_residue_identity_agreement"] is False
    assert result["matrix_comparison"]["maximum_error_angstrom"] > 1

    selected, altlocs, count = select_atom_alternate_locations(
        {
            "CA": [
                ("A", 0.4, np.asarray([1.0, 0.0, 0.0])),
                ("B", 0.8, np.asarray([2.0, 0.0, 0.0])),
            ]
        }
    )
    assert count == 1
    assert altlocs["CA"] == "B"
    assert selected["CA"][0] == 2


def test_local_frame_is_right_handed_but_not_native_chirality_evidence() -> None:
    residue = _residue(0)
    frame, determinant = local_frame(residue.atoms["N"], residue.atoms["CA"], residue.atoms["C"])
    assert determinant == pytest.approx(1)
    assert frame_is_right_handed(frame)
    quality = frame_quality(frame)
    assert quality["frame_valid"] is True
    assert quality["frame_orthogonality_error"] < 1e-12
    assert quality["frame_unit_norm_error"] < 1e-12
    reflected = frame.copy()
    reflected[:, 2] *= -1
    assert not frame_is_right_handed(reflected)
    assert compare_ca_distance_matrix([residue], np.zeros((1, 1)))["comparable"] is False


@pytest.mark.parametrize("name,one_letter", [("ALA", "A"), ("ARG", "R")])
def test_fixed_canonical_l_coordinates_use_positive_native_chirality(name: str, one_letter: str) -> None:
    residue = _residue(0, name=name, one_letter=one_letter)
    signed = native_chirality_signed_volume(
        residue.atoms["N"], residue.atoms["CA"], residue.atoms["C"], residue.atoms["CB"]
    )
    diagnostic = residue_geometry_diagnostics(residue)
    assert signed > 0
    assert diagnostic["native_chirality_available"] is True
    assert diagnostic["native_chirality_valid"] is True
    assert diagnostic["chirality_convention_version"] == CHIRALITY_CONVENTION_VERSION
    # The v1 defect expected this same documented scalar to be negative.
    assert (signed < 0) is False


def test_native_chirality_is_rigid_transform_invariant_and_reflection_sensitive() -> None:
    residue = _residue(0)
    angle = np.deg2rad(37.0)
    rotation = np.asarray([[np.cos(angle), -np.sin(angle), 0.0], [np.sin(angle), np.cos(angle), 0.0], [0.0, 0.0, 1.0]])
    translation = np.asarray([8.0, -3.0, 2.5])
    transformed_atoms = {name: rotation @ value + translation for name, value in residue.atoms.items()}
    transformed = BackboneResidue("ALA", "A", "1", "", transformed_atoms)
    base = native_chirality_signed_volume(
        residue.atoms["N"], residue.atoms["CA"], residue.atoms["C"], residue.atoms["CB"]
    )
    moved = native_chirality_signed_volume(
        transformed.atoms["N"], transformed.atoms["CA"], transformed.atoms["C"], transformed.atoms["CB"]
    )
    assert moved == pytest.approx(base)
    assert residue_geometry_diagnostics(transformed)["native_chirality_valid"] is True

    reflected_atoms = {name: value * np.asarray([1.0, 1.0, -1.0]) for name, value in residue.atoms.items()}
    reflected = BackboneResidue("ALA", "A", "1", "", reflected_atoms)
    reflected_diagnostic = residue_geometry_diagnostics(reflected)
    assert reflected_diagnostic["frame_valid"] is True
    assert reflected_diagnostic["native_chirality_signed_volume"] == pytest.approx(-base)
    assert reflected_diagnostic["native_chirality_valid"] is False

    swapped_atoms = dict(residue.atoms)
    swapped_atoms["N"], swapped_atoms["C"] = swapped_atoms["C"], swapped_atoms["N"]
    assert (
        residue_geometry_diagnostics(BackboneResidue("ALA", "A", "1", "", swapped_atoms))["native_chirality_valid"]
        is False
    )


def test_chirality_availability_classes_and_explicit_d_configuration() -> None:
    glycine = _residue(0, name="GLY", missing="CB")
    missing_cb = _residue(0, missing="CB")
    noncanonical = _residue(0, name="UNK", one_letter=None, chirality_class="noncanonical_unknown")
    for residue, reason in (
        (glycine, "glycine_achiral"),
        (missing_cb, "native_cb_unavailable"),
        (noncanonical, "noncanonical_configuration_unknown"),
    ):
        diagnostic = residue_geometry_diagnostics(residue)
        assert diagnostic["native_chirality_available"] is False
        assert diagnostic["native_chirality_valid"] is None
        assert diagnostic["chirality_reason"] == reason

    l_residue = _residue(0)
    reflected_atoms = {name: value * np.asarray([1.0, 1.0, -1.0]) for name, value in l_residue.atoms.items()}
    d_residue = BackboneResidue("DAL", "A", "1", "", reflected_atoms, chirality_class="explicit_d")
    diagnostic = residue_geometry_diagnostics(d_residue)
    assert diagnostic["native_chirality_signed_volume"] < 0
    assert diagnostic["native_chirality_valid"] is True


def test_pseudo_cb_agreement_is_independent_of_native_chirality() -> None:
    residue = _residue(0)
    matching = residue_geometry_diagnostics(residue)
    assert matching["pseudo_cb_available"] is True
    assert matching["pseudo_cb_native_distance_angstrom"] == pytest.approx(0.00737, abs=1e-4)
    assert matching["pseudo_cb_agreement"] is True
    atoms = dict(residue.atoms)
    atoms["CB"] = atoms["CB"] + np.asarray([2.0, 0.0, 0.0])
    disagreeing = residue_geometry_diagnostics(BackboneResidue("ALA", "A", "1", "", atoms))
    assert disagreeing["native_chirality_valid"] is True
    assert disagreeing["pseudo_cb_agreement"] is False


def test_degenerate_frame_and_missing_cb_do_not_create_chirality_contradictions() -> None:
    collinear = BackboneResidue(
        "ALA",
        "A",
        "1",
        "",
        {
            "N": np.asarray([-1.0, 0.0, 0.0]),
            "CA": np.zeros(3),
            "C": np.asarray([1.0, 0.0, 0.0]),
            "CB": np.asarray([0.0, 1.0, 0.0]),
        },
    )
    diagnostic = residue_geometry_diagnostics(collinear)
    assert diagnostic["frame_valid"] is False
    assert diagnostic["native_chirality_available"] is False
    result = analyze_backbone_residues([collinear], expected_sequence="A", stored_matrix=np.zeros((1, 1)))
    assert result["invalid_chirality_count"] == 0
    assert "chirality_contradiction" not in result["unavailable_reasons"]

    missing = _residue(0, missing="CB")
    result = analyze_backbone_residues([missing], expected_sequence="A", stored_matrix=np.zeros((1, 1)))
    assert result["chirality_eligible_residue_count"] == 0
    assert "chirality_contradiction" not in result["unavailable_reasons"]


def test_verified_target_mapping_ignores_unaligned_components_and_maps_authoritative_mse() -> None:
    extra = replace(_target_residue(8, name="UNK", one_letter=None), auth_sequence_id="99")
    mse = _target_residue(0, name="MSE", one_letter="M", parent="MET")
    alanine = _target_residue(1)
    mapping = _resolve([extra, mse, alanine], "MA")
    assert mapping["mapping_verified"] is True
    assert mapping["observed_target_sequence"] == "MA"
    assert mapping["target_residue_classifications"] == [
        "mapped_modified_target_residue",
        "canonical_target_residue",
    ]
    assert mapping["ignored_unmapped_source_component_count"] == 1
    assert "UNK" in mapping["ignored_unmapped_source_components_json"]
    assert mapping["mapping_version"] == TARGET_MAPPING_POLICY_VERSION
    assert mapping["canonicalization_version"] == CANONICALIZATION_POLICY_VERSION


def test_target_modification_requires_authoritative_parent_and_pairing_provenance() -> None:
    unknown = _target_residue(0, name="AYA", one_letter=None)
    mapping = _resolve([unknown], "A")
    assert mapping["mapping_verified"] is False
    assert "unresolved_target_modification" in mapping["mapping_errors"]
    analysis = analyze_backbone_residues(
        mapping["target_residues"], expected_sequence="A", stored_matrix=np.zeros((1, 1))
    )
    decision = resolve_rich_geometry_eligibility(mapping, analysis)
    assert decision["exclusion_reason"] == "excluded_unresolved_target_modification"

    parent_without_pairing_provenance = resolve_verified_target_mapping(
        [_target_residue(0, name="MSE", one_letter="M", parent="MET")],
        sample_id="mse-without-provenance",
        expected_sequence="M",
        residue_ids='["1"]',
        insertion_codes='[""]',
        residue_id_convention="auth_seq_id_insertion",
        pairing_canonicalization_version=None,
    )
    assert "unresolved_target_modification" in parent_without_pairing_provenance["mapping_errors"]


def test_missing_non_calpha_atoms_are_masked_without_exclusion() -> None:
    residues = [_target_residue(0), _target_residue(1, missing="O")]
    mapping = _resolve(residues, "AA")
    assert mapping["mapping_verified"] is True
    assert mapping["masked_missing_atom_residue_count"] == 1
    assert mapping["target_residue_classifications"][1] == "masked_target_missing_atoms"
    analysis = analyze_backbone_residues(residues, expected_sequence="AA", stored_matrix=_matrix(residues))
    decision = resolve_rich_geometry_eligibility(mapping, analysis)
    assert decision["rich_geometry_eligible"] is True
    assert decision["unexplained_contradiction_count"] == 0

    missing_ca = [_target_residue(0), _target_residue(1, missing="CA")]
    mapping = _resolve(missing_ca, "AA")
    assert mapping["mapping_verified"] is True


def test_exact_ids_gaps_insertions_and_zero_author_numbering_anchor_in_order(tmp_path: Path) -> None:
    identifiers = ["0", "2", "321", "321"]
    insertions = ["", "", "", "A"]
    residues = []
    for index, (identifier, insertion) in enumerate(zip(identifiers, insertions, strict=True)):
        residue = replace(
            _target_residue(index),
            auth_sequence_id=identifier,
            residue_number=identifier,
            insertion_code=insertion,
        )
        residues.append(residue)
    mapping = resolve_verified_target_mapping(
        residues,
        sample_id="numbering",
        expected_sequence="AAAA",
        residue_ids=json.dumps(identifiers),
        insertion_codes=json.dumps(insertions),
        residue_id_convention="auth_seq_id_insertion",
        pairing_canonicalization_version="sequence_geometry_pairing_v1",
    )
    assert mapping["mapping_verified"] is True
    assert mapping["resolved_target_residue_ids"] == ["0", "2", "321", "321A"]
    coordinates = np.stack([residue.atoms["CA"] for residue in residues])
    npz = _write_npz_evidence(tmp_path, ["0", "2", "321", "321A"], coordinates)
    anchored = reconcile_npz_calpha_anchors(
        mapping["target_residues"],
        resolved_target_residue_ids=mapping["resolved_target_residue_ids"],
        npz=npz,
    )
    assert anchored["npz_residue_id_order_agreement"] is True
    assert anchored["uniquely_anchored_residue_count"] == 4
    assert anchored["source_to_npz_calpha_anchor_consistency"] is True


def test_npz_anchor_selects_blank_ca_over_higher_occupancy_nonblank(tmp_path: Path) -> None:
    residue = _target_residue(0)
    blank_ca = residue.atoms["CA"]
    candidates = {atom: [(None, 0.4, coordinate)] for atom, coordinate in residue.atoms.items()}
    candidates["CA"].append(("B", 0.9, blank_ca + np.asarray([1.0, 0.0, 0.0])))
    residue = _with_atom_candidates(residue, candidates)
    npz = _write_npz_evidence(tmp_path, ["1"], np.asarray([blank_ca]))
    result = reconcile_npz_calpha_anchors([residue], resolved_target_residue_ids=["1"], npz=npz)
    assert result["source_to_npz_calpha_anchor_consistency"] is True
    assert json.loads(result["selected_calpha_conformers_json"]) == [None]
    assert result["conflicting_nonblank_conformer_count"] >= 1


def test_nonblank_anchor_uses_shared_blank_atoms_without_mixing_conformers(tmp_path: Path) -> None:
    residue = _target_residue(0)
    ca_b = residue.atoms["CA"] + np.asarray([0.2, 0.0, 0.0])
    candidates = {
        "CA": [("A", 0.8, residue.atoms["CA"]), ("B", 0.4, ca_b)],
        "N": [(None, 1.0, residue.atoms["N"]), ("A", 0.8, residue.atoms["N"] + 5)],
        "C": [(None, 1.0, residue.atoms["C"])],
        "O": [(None, 1.0, residue.atoms["O"])],
        "CB": [(None, 1.0, residue.atoms["CB"])],
    }
    residue = _with_atom_candidates(residue, candidates)
    npz = _write_npz_evidence(tmp_path, ["1"], np.asarray([ca_b]))
    result = reconcile_npz_calpha_anchors([residue], resolved_target_residue_ids=["1"], npz=npz)
    [anchored] = result["_anchored_residues"]
    assert json.loads(result["selected_calpha_conformers_json"]) == ["B"]
    assert result["blank_altloc_fallback_count"] == 4
    assert result["conflicting_nonblank_conformer_count"] == 2
    assert "N" in anchored.atoms
    assert anchored.selected_altlocs["N"] is None


def test_missing_ambiguous_and_coordinate_mismatched_anchors_are_distinct(tmp_path: Path) -> None:
    base = _target_residue(0)
    npz = _write_npz_evidence(tmp_path, ["1"], np.asarray([base.atoms["CA"]]))
    missing = reconcile_npz_calpha_anchors(
        [replace(base, atoms={key: value for key, value in base.atoms.items() if key != "CA"})],
        resolved_target_residue_ids=["1"],
        npz=npz,
    )
    assert missing["coordinate_anchor_exclusion_reason"] == "excluded_npz_calpha_anchor_unavailable"
    mapping = _resolve([base], "A")
    mapping.update({key: value for key, value in missing.items() if key != "_anchored_residues"})
    decision = resolve_rich_geometry_eligibility(mapping, {})
    assert decision["exclusion_reason"] == "excluded_npz_calpha_anchor_unavailable"
    assert decision["unexplained_contradiction_count"] == 0

    equal_candidates = _with_atom_candidates(
        base,
        {"CA": [("A", 0.5, base.atoms["CA"]), ("B", 0.5, base.atoms["CA"])]},
    )
    ambiguous = reconcile_npz_calpha_anchors([equal_candidates], resolved_target_residue_ids=["1"], npz=npz)
    assert ambiguous["coordinate_anchor_exclusion_reason"] == "excluded_npz_calpha_anchor_ambiguous"

    shifted = _with_atom_candidates(
        base,
        {"CA": [(None, 1.0, base.atoms["CA"] + np.asarray([1.0, 0.0, 0.0]))]},
    )
    mismatch = reconcile_npz_calpha_anchors([shifted], resolved_target_residue_ids=["1"], npz=npz)
    assert mismatch["coordinate_anchor_exclusion_reason"] == ("excluded_source_npz_coordinate_contradiction")


def test_npz_order_and_internal_geometry_contradictions_are_distinct(tmp_path: Path) -> None:
    residues = [_target_residue(0), _target_residue(1)]
    coordinates = np.stack([residue.atoms["CA"] for residue in residues])
    permuted = _write_npz_evidence(tmp_path, ["2", "1"], coordinates[::-1])
    order = reconcile_npz_calpha_anchors(residues, resolved_target_residue_ids=["1", "2"], npz=permuted)
    assert order["coordinate_anchor_exclusion_reason"] == "excluded_npz_residue_order_contradiction"

    inconsistent = _write_npz_evidence(
        tmp_path,
        ["1", "2"],
        coordinates,
        matrix=np.asarray([[0.0, 99.0], [99.0, 0.0]]),
    )
    assert inconsistent.internal_consistent is False
    internal = reconcile_npz_calpha_anchors(residues, resolved_target_residue_ids=["1", "2"], npz=inconsistent)
    assert internal["coordinate_anchor_exclusion_reason"] == ("excluded_npz_internal_geometry_contradiction")


def test_source_hash_provenance_matches_or_excludes(tmp_path: Path) -> None:
    residue = _target_residue(0)
    npz = _write_npz_evidence(tmp_path, ["1"], np.asarray([residue.atoms["CA"]]))
    common = {
        "residues": [residue],
        "resolved_target_residue_ids": ["1"],
        "npz": npz,
        "actual_source_sha256": "a" * 64,
    }
    matching = reconcile_npz_calpha_anchors(**common, recorded_source_sha256="a" * 64)
    assert matching["coordinate_anchor_exclusion_reason"] is None
    assert matching["source_sha256_agreement"] is True
    mismatching = reconcile_npz_calpha_anchors(**common, recorded_source_sha256="b" * 64)
    assert mismatching["coordinate_anchor_exclusion_reason"] == ("excluded_source_npz_coordinate_contradiction")
    assert mismatching["source_sha256_agreement"] is False


def test_anchor_failure_examples_are_bounded(tmp_path: Path) -> None:
    residues = [replace(_target_residue(index), atoms={}) for index in range(5)]
    coordinates = np.stack([_target_residue(index).atoms["CA"] for index in range(5)])
    npz = _write_npz_evidence(tmp_path, [str(index + 1) for index in range(5)], coordinates)
    result = reconcile_npz_calpha_anchors(
        residues,
        resolved_target_residue_ids=[str(index + 1) for index in range(5)],
        npz=npz,
        maximum_examples=2,
    )
    examples = json.loads(result["coordinate_anchor_failure_examples_json"])
    assert result["unavailable_calpha_anchor_count"] == 5
    assert len(examples["npz_calpha_anchor_unavailable"]) == 2


def test_severe_identity_mismatch_and_native_inversion_are_resolved_exclusions() -> None:
    severe_residues = [_target_residue(index) for index in range(100)]
    mismatch = _resolve(severe_residues, "AAA" + "G" * 97)
    identity_matches = sum(
        left == right for left, right in zip(mismatch["observed_target_sequence"], "AAA" + "G" * 97, strict=True)
    )
    assert identity_matches / 100 == 0.03
    assert "target_sequence_identity_mismatch" in mismatch["mapping_errors"]
    mismatch_decision = resolve_rich_geometry_eligibility(mismatch, {})
    assert mismatch_decision["exclusion_reason"] == "excluded_identity_mapping_contradiction"

    residue = _target_residue(0)
    reflected_atoms = {name: value * np.asarray([1.0, 1.0, -1.0]) for name, value in residue.atoms.items()}
    inverted = replace(residue, atoms=reflected_atoms)
    mapping = _resolve([inverted], "A")
    analysis = analyze_backbone_residues([inverted], expected_sequence="A", stored_matrix=np.zeros((1, 1)))
    decision = resolve_rich_geometry_eligibility(mapping, analysis)
    evidence = json.loads(analysis["residue_geometry_records_json"])[0]
    assert evidence["residue_id"] == "1"
    assert evidence["native_chirality_signed_volume"] < 0
    assert decision["exclusion_reason"] == "excluded_stereochemical_contradiction"
    assert decision["resolved_exclusion_count"] == 1
    assert decision["unexplained_contradiction_count"] == 0


def test_phase1_authorizes_attested_subset_without_hiding_exclusions() -> None:
    eligible = {
        "sample_id": "eligible",
        "rich_geometry_eligible": True,
        "source_coordinates_verified": True,
        "sequence_length": 10,
        "residue_identity_match_fraction": 1.0,
        "complete_local_frame_fraction": 1.0,
        "phi_computable_fraction": 1.0,
        "psi_computable_fraction": 1.0,
        "matrix_valid_pair_count": 45,
        "matrix_rmse_angstrom": 0.0,
        "unexplained_contradiction_count": 0,
        "resolved_exclusion_count": 0,
    }
    excluded = {
        **eligible,
        "sample_id": "excluded",
        "rich_geometry_eligible": False,
        "source_coordinates_verified": True,
        "residue_identity_match_fraction": 0.03,
        "resolved_exclusion_count": 1,
    }
    authorization = _authorization([eligible, excluded])
    assert authorization["authorized"] is True
    assert authorization["values"]["mapped_identity_fraction"] == 1.0
    assert authorization["authorization_population"] == {
        "audit_panel_sample_count": 2,
        "eligible_subset_count": 1,
        "resolved_excluded_count": 1,
        "unexplained_record_count": 0,
        "denominator_policy": "coverage gates use only explicitly eligible records; all exclusions remain counted",
    }
    assert eligibility_counts([eligible, excluded])["rich_geometry_excluded_count"] == 1


def test_phase1_recomputes_coverage_only_from_verified_anchor_denominator() -> None:
    anchored = {
        "sample_id": "anchored",
        "rich_geometry_eligible": True,
        "source_coordinates_verified": True,
        "npz_internal_matrix_consistency": True,
        "source_to_npz_calpha_anchor_consistency": True,
        "uniquely_anchored_residue_count": 10,
        "sequence_length": 10,
        "residue_identity_match_fraction": 1.0,
        "complete_local_frame_fraction": 1.0,
        "phi_computable_fraction": 1.0,
        "psi_computable_fraction": 1.0,
        "source_to_npz_calpha_coordinate_rmse_angstrom": 0.01,
        "unexplained_contradiction_count": 0,
        "resolved_exclusion_count": 0,
    }
    unanchored = {
        **anchored,
        "sample_id": "unanchored",
        "source_to_npz_calpha_anchor_consistency": False,
        "residue_identity_match_fraction": 0.0,
    }
    authorization = _authorization([anchored, unanchored])
    assert authorization["values"]["mapped_identity_fraction"] == 1.0
    assert authorization["values"]["matrix_rmse_angstrom"] == pytest.approx(0.01)
    assert authorization["checks"]["npz_internal_matrix_consistency"] is True
    assert authorization["checks"]["source_to_npz_calpha_anchor_consistency"] is False
    assert authorization["authorized"] is False


def test_eligibility_manifest_has_required_provenance_and_is_one_row_per_sample() -> None:
    rows = eligibility_manifest_rows(
        [
            {
                "sample_id": "sample",
                "split": "train",
                "sequence": "AA",
                "rich_geometry_eligible": False,
                "exclusion_reason": "excluded_stereochemical_contradiction",
                "source_file": "/immutable/source.cif",
                "source_sha256": "source-hash",
                "matrix_sha256": "matrix-hash",
                "model_number": 1,
                "chain_id": "C",
                "complete_local_frame_fraction": 1.0,
                "local_frame_mask_json": "[true,true]",
            }
        ]
    )
    assert len(rows) == 1
    assert rows[0]["eligible"] is False
    assert rows[0]["mapping_version"] == TARGET_MAPPING_POLICY_VERSION
    assert rows[0]["chirality_version"] == CHIRALITY_CONVENTION_VERSION
    assert rows[0]["coordinate_anchor_policy_version"] == COORDINATE_ANCHOR_POLICY_VERSION


def test_panel_counts_and_full_corpus_projection_are_explicitly_distinct() -> None:
    records = [
        {"rich_geometry_eligible": True},
        {"rich_geometry_eligible": True},
        {"rich_geometry_eligible": False},
        {"rich_geometry_eligible": False},
    ]
    projection = project_full_corpus_eligibility(
        records,
        {"train": {"filtered_candidate_count": 80}, "validation": {"filtered_candidate_count": 20}},
    )
    assert projection["audit_panel_sample_count"] == 4
    assert projection["scanned_filtered_candidate_count"] == 100
    assert projection["projected_rich_geometry_eligible_count"] == 50
    assert projection["definitive_full_corpus_counts"] is False


def _cif_row(
    atom_id: int,
    atom: str,
    residue: str,
    sequence_id: int,
    xyz: tuple[float, float, float],
    *,
    model: int,
    insertion: str = "?",
    altloc: str = ".",
    occupancy: float = 1.0,
) -> str:
    element = atom[0]
    return (
        f"ATOM {atom_id} {element} {atom} {altloc} {residue} A 1 {sequence_id} {insertion} "
        f"{xyz[0]} {xyz[1]} {xyz[2]} {occupancy} 20 ? {sequence_id} {residue} A {atom} {model}"
    )


def _write_ensemble(path: Path) -> None:
    tags = """data_ENSEMBLE
loop_
_atom_site.group_PDB
_atom_site.id
_atom_site.type_symbol
_atom_site.label_atom_id
_atom_site.label_alt_id
_atom_site.label_comp_id
_atom_site.label_asym_id
_atom_site.label_entity_id
_atom_site.label_seq_id
_atom_site.pdbx_PDB_ins_code
_atom_site.Cartn_x
_atom_site.Cartn_y
_atom_site.Cartn_z
_atom_site.occupancy
_atom_site.B_iso_or_equiv
_atom_site.pdbx_formal_charge
_atom_site.auth_seq_id
_atom_site.auth_comp_id
_atom_site.auth_asym_id
_atom_site.auth_atom_id
_atom_site.pdbx_PDB_model_num
"""
    rows = []
    atom_id = 1
    for model in (1, 2):
        for sequence_id, residue in ((1, "GLY"), (2, "ALA")):
            base = 4.0 * (sequence_id - 1)
            for atom, xyz in (
                ("N", (base, 0.0, 0.0)),
                ("CA", (base + 1.3, 0.7, 0.1)),
                ("C", (base + 2.7, 0.2, 0.6)),
                ("O", (base + 3.2, -0.5, 0.7)),
            ):
                insertion = "A" if sequence_id == 2 else "?"
                rows.append(_cif_row(atom_id, atom, residue, sequence_id, xyz, model=model, insertion=insertion))
                atom_id += 1
            if sequence_id == 1:
                rows.append(
                    _cif_row(
                        atom_id,
                        "CA",
                        residue,
                        sequence_id,
                        (base + 1.4, 0.8, 0.1),
                        model=model,
                        altloc="B",
                        occupancy=0.2,
                    )
                )
                atom_id += 1
    path.write_text(tags + "\n".join(rows) + "\n#\n")


def _write_modified_polymer_with_ligand(path: Path) -> None:
    header = """data_MODIFIED
loop_
_chem_comp.id
_chem_comp.type
_chem_comp.mon_nstd_parent_comp_id
ALA 'L-peptide linking' ?
MSE 'L-peptide linking' MET
LIG non-polymer ?
#
loop_
_pdbx_poly_seq_scheme.asym_id
_pdbx_poly_seq_scheme.entity_id
_pdbx_poly_seq_scheme.seq_id
_pdbx_poly_seq_scheme.mon_id
_pdbx_poly_seq_scheme.pdb_strand_id
_pdbx_poly_seq_scheme.auth_seq_num
_pdbx_poly_seq_scheme.pdb_ins_code
A 1 1 MSE A 1 ?
A 1 2 ALA A 2 ?
#
loop_
_atom_site.group_PDB
_atom_site.id
_atom_site.type_symbol
_atom_site.label_atom_id
_atom_site.label_alt_id
_atom_site.label_comp_id
_atom_site.label_asym_id
_atom_site.label_entity_id
_atom_site.label_seq_id
_atom_site.pdbx_PDB_ins_code
_atom_site.Cartn_x
_atom_site.Cartn_y
_atom_site.Cartn_z
_atom_site.occupancy
_atom_site.B_iso_or_equiv
_atom_site.pdbx_formal_charge
_atom_site.auth_seq_id
_atom_site.auth_comp_id
_atom_site.auth_asym_id
_atom_site.auth_atom_id
_atom_site.pdbx_PDB_model_num
"""
    rows = []
    atom_id = 1
    for sequence_id, residue in enumerate(("MSE", "ALA"), start=1):
        for atom, xyz in (
            ("N", (-0.525 + 3.38 * (sequence_id - 1), 1.363, 0.0)),
            ("CA", (3.38 * (sequence_id - 1), 0.0, 0.0)),
            ("C", (1.526 + 3.38 * (sequence_id - 1), 0.0, 0.0)),
            ("O", (2.153 + 3.38 * (sequence_id - 1), -1.062, 0.0)),
            ("CB", (-0.529 + 3.38 * (sequence_id - 1), -0.774, -1.205)),
        ):
            rows.append(_cif_row(atom_id, atom, residue, sequence_id, xyz, model=1))
            atom_id += 1
    rows.append("HETATM 11 C C1 . LIG A 2 . ? 20 20 20 1.0 20 ? 900 LIG A C1 1")
    path.write_text(header + "\n".join(rows) + "\n#\n")


def test_real_gemmi_mmcif_multiple_nmr_models_altloc_and_insertion(tmp_path: Path) -> None:
    path = tmp_path / "ensemble.cif"
    _write_ensemble(path)
    residues, metadata = parse_backbone_mmcif(path, chain_id="A", model_number=1)
    assert [residue.one_letter for residue in residues] == ["G", "A"]
    assert residues[1].insertion_code == "A"
    assert residues[0].alternate_location_count == 1
    assert len(residues[0].atom_candidates["CA"]) == 2
    assert metadata["nmr_model_count"] == 2
    assert metadata["selected_model_number"] == 1
    assert metadata["cross_model_sequence_consistent"] is True


def test_real_gemmi_authoritative_parent_and_nonpolymer_membership(tmp_path: Path) -> None:
    path = tmp_path / "modified.cif"
    _write_modified_polymer_with_ligand(path)
    residues, metadata = parse_backbone_mmcif(path, chain_id="A", model_number=1, residue_mappings={"MSE": "MET"})
    assert [residue.residue_name for residue in residues] == ["MSE", "ALA"]
    assert residues[0].authoritative_parent_comp_id == "MET"
    assert residues[0].authoritative_parent_source == "_chem_comp.mon_nstd_parent_comp_id"
    assert residues[0].chirality_class == "mapped_modified_l"
    assert metadata["ignored_source_component_count"] == 1
    assert "LIG" in metadata["ignored_source_components_json"]
    assert metadata["configured_residue_name_mappings_are_authoritative"] is False


def test_mmcif_is_read_once_and_plain_gzip_parsing_are_equivalent(tmp_path: Path) -> None:
    plain = tmp_path / "modified.cif"
    compressed = tmp_path / "modified.cif.gz"
    _write_modified_polymer_with_ligand(plain)
    with plain.open("rb") as source, gzip.open(compressed, "wb") as destination:
        destination.write(source.read())
    observations = []
    plain_residues, plain_metadata = parse_backbone_mmcif(plain, chain_id="A", model_number=1)
    legacy_residues, legacy_metadata = parse_backbone_mmcif(
        plain,
        chain_id="A",
        model_number=1,
        parse_mode="legacy_double_parse",
    )
    gzip_residues, gzip_metadata = parse_backbone_mmcif(
        compressed,
        chain_id="A",
        model_number=1,
        stage_observer=lambda stage, seconds, bytes_read, bytes_written: observations.append(
            (stage, seconds, bytes_read, bytes_written)
        ),
    )
    assert [residue.residue_name for residue in gzip_residues] == [residue.residue_name for residue in plain_residues]
    assert [residue.atoms.keys() for residue in gzip_residues] == [residue.atoms.keys() for residue in plain_residues]
    for gzip_residue, plain_residue in zip(gzip_residues, plain_residues, strict=True):
        for atom in gzip_residue.atoms:
            assert np.array_equal(gzip_residue.atoms[atom], plain_residue.atoms[atom])
    assert {key: value for key, value in gzip_metadata.items() if key != "_model_residues"} == {
        key: value for key, value in plain_metadata.items() if key != "_model_residues"
    }
    assert [residue.residue_name for residue in legacy_residues] == [residue.residue_name for residue in plain_residues]
    assert [
        (residue.residue_number, residue.insertion_code, residue.label_sequence_id, residue.auth_sequence_id)
        for residue in legacy_residues
    ] == [
        (residue.residue_number, residue.insertion_code, residue.label_sequence_id, residue.auth_sequence_id)
        for residue in plain_residues
    ]
    for legacy_residue, plain_residue in zip(legacy_residues, plain_residues, strict=True):
        assert legacy_residue.atoms.keys() == plain_residue.atoms.keys()
        for atom in legacy_residue.atoms:
            assert np.array_equal(legacy_residue.atoms[atom], plain_residue.atoms[atom])
    assert {key: value for key, value in legacy_metadata.items() if key != "_model_residues"} == {
        key: value for key, value in plain_metadata.items() if key != "_model_residues"
    }
    assert [item[0] for item in observations] == ["mmcif_gzip_reading", "gemmi_parsing"]
    assert all(item[1] >= 0 and item[2] > 0 and item[3] == 0 for item in observations)


def _selection_rows(counts: list[int]) -> list[dict[str, object]]:
    rows = []
    index = 0
    for group, count in enumerate(counts):
        for _ in range(count):
            rows.append(
                {
                    "sample_id": f"sample-{index:04d}",
                    "split": "train" if index % 2 else "validation",
                    "length_bin": f"length-{group}",
                    "experimental_method": f"method-{group}",
                    "pairing_classification": f"class-{group}",
                }
            )
            index += 1
    return rows


def test_sparse_stratified_redistribution_is_stable_and_duplicate_safe() -> None:
    rows = _selection_rows([1, 2, 20])
    selected, diagnostics = stratified_select(
        rows,
        target=12,
        seed=6,
        stratum_fields=("length_bin", "experimental_method", "pairing_classification"),
    )
    reversed_selected, _ = stratified_select(
        list(reversed(rows)),
        target=12,
        seed=6,
        stratum_fields=("length_bin", "experimental_method", "pairing_classification"),
    )
    assert [row["sample_id"] for row in selected] == [row["sample_id"] for row in reversed_selected]
    assert diagnostics["initially_stratified_count"] == 7
    assert diagnostics["backfilled_count"] == 5
    duplicated, duplicate_diagnostics = stratified_select(
        [*rows, dict(rows[0])],
        target=12,
        seed=6,
        stratum_fields=("length_bin", "experimental_method", "pairing_classification"),
    )
    assert len(duplicated) == 12
    assert duplicate_diagnostics["duplicate_sample_id_count"] == 1
    with pytest.raises(ValueError, match="conflicting_duplicate"):
        stratified_select(
            [*rows, {**rows[0], "experimental_method": "other"}],
            target=12,
            seed=6,
            stratum_fields=("length_bin", "experimental_method", "pairing_classification"),
        )


def test_schema_inventory_uses_metadata_and_path_traversal_is_rejected(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    root = tmp_path / "root"
    root.mkdir()
    parquet = root / "manifest.parquet"
    pq.write_table(pa.table({"sample_id": ["a", "b"], "sequence": ["AA", "GG"]}), parquet)
    monkeypatch.setattr(pq, "read_table", lambda *args, **kwargs: pytest.fail("table materialized"))
    inventory = parquet_schema_inventory("manifest", parquet)
    assert inventory["row_count"] == 2
    assert inventory["schema"][0]["name"] == "sample_id"
    assert resolve_within_roots(parquet, [root]) == parquet.resolve()
    outside = tmp_path / "outside.cif"
    outside.write_text("data_x\n")
    with pytest.raises(ValueError, match="outside_protected_roots"):
        resolve_within_roots(outside, [root])


def test_partition_panel_scan_is_projected_bounded_and_order_independent(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    rows = [
        {
            "sample_id": f"sample-{index:04d}",
            "schema_version": "sequence_geometry_pairing_v1",
            "sequence": "A" * 32,
            "sequence_length": 32,
            "matrix_path": f"/unused/{index}.npz",
            "practical_training_eligibility": "strict_verified_pair",
            "experimental_method": f"method-{index % 4}",
            "pairing_classification": f"class-{index % 3}",
            "large_nested_unused": [{"index": index}],
        }
        for index in range(1000)
    ]
    first = tmp_path / "first"
    second = tmp_path / "second"
    first.mkdir()
    second.mkdir()
    for fragment in range(5):
        pq.write_table(pa.Table.from_pylist(rows[fragment::5]), first / f"part-{fragment}.parquet")
        pq.write_table(pa.Table.from_pylist(list(reversed(rows))[fragment::5]), second / f"part-{fragment}.parquet")
    monkeypatch.setattr(pq, "read_table", lambda *args, **kwargs: pytest.fail("full table materialized"))
    selected_a, diagnostics_a = scan_stratified_partition(first, split="train", target=64, seed=8, batch_size=7)
    selected_b, diagnostics_b = scan_stratified_partition(second, split="train", target=64, seed=8, batch_size=4096)
    assert [row["sample_id"] for row in selected_a] == [row["sample_id"] for row in selected_b]
    assert diagnostics_a["filtered_candidate_count"] == diagnostics_b["filtered_candidate_count"] == 1000
    assert len(selected_a) == 64
    assert all("large_nested_unused" not in row for row in selected_a)


def _authorization(records: list[dict[str, object]]) -> dict[str, object]:
    return phase1_authorization(
        records,
        {
            "minimum_verified_source_fraction": 0.95,
            "minimum_mapped_identity_fraction": 0.98,
            "minimum_complete_frame_fraction": 0.90,
            "minimum_phi_psi_fraction": 0.85,
            "maximum_matrix_rmse_angstrom": 0.05,
            "maximum_unexplained_contradictions": 0,
        },
    )


def test_atomic_publication_heartbeat_memory_and_input_preservation(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    protected = tmp_path / "input.cif"
    protected.write_text("immutable")
    before = sha256_file(protected)
    record = {
        "sample_id": "sample-a",
        "experimental_method": "X-RAY DIFFRACTION",
        "length_bin": "le_64",
        "pairing_classification": "unique",
        "source_coordinates_verified": True,
        "sequence_length": 2,
        "residue_identity_match_fraction": 1.0,
        "complete_local_frame_fraction": 1.0,
        "phi_computable_fraction": 1.0,
        "psi_computable_fraction": 1.0,
        "matrix_valid_pair_count": 1,
        "matrix_rmse_angstrom": 0.0,
        "unexplained_contradiction_count": 0,
        "unavailable_reasons": [],
    }
    output = tmp_path / "completed"
    protocol = {
        "schema_version": AUDIT_SCHEMA_VERSION,
        "input_hashes_before": {str(protected): before},
        "input_hashes_after": {str(protected): before},
        "dataset_inputs_unchanged": True,
        "storage_estimates": sidecar_storage_estimates([64]),
        "phase1_authorization": _authorization([record]),
    }
    completed = publish_audit_outputs(
        output,
        records=[record],
        schema_inventory={"manifest": {"schema": []}},
        protocol=protocol,
    )
    assert completed["status"] == "completed"
    assert json.loads((output / "protocol.json").read_text())["authorizes_phase1"] is True
    assert not list(output.glob("*.tmp"))
    assert sha256_file(protected) == before

    heartbeat = AuditHeartbeat(output / "heartbeat.json", 4)
    running = heartbeat.update("source_validation", 1)
    assert running["percentage"] == 25
    final = heartbeat.update("finalization", 4, status="completed")
    assert final["percentage"] == 100

    failure_output = tmp_path / "failed"
    failed = write_failed_protocol(
        failure_output,
        {"schema_version": AUDIT_SCHEMA_VERSION, "input_hashes_before": {str(protected): before}},
        RuntimeError("synthetic failure" + "x" * 1000),
        failure_context={"stage": "target_mapping", "sample_id": "sample-a", "field_name": "residue_ids"},
    )
    assert failed["status"] == "failed"
    assert failed["authorizes_phase1"] is False
    assert failed["dataset_inputs_unchanged"] is True
    assert failed["failure"]["stage"] == "target_mapping"
    assert failed["failure"]["sample_id"] == "sample-a"
    assert failed["failure"]["field_name"] == "residue_ids"
    assert len(failed["failure"]["message"]) == 500

    monkeypatch.setattr("protein_distance_diffusion.evaluation.e006_geometry_source_audit._rss_mib", lambda: 101.0)
    monkeypatch.setattr("protein_distance_diffusion.evaluation.e006_geometry_source_audit._peak_rss_mib", lambda: 102.0)
    with pytest.raises(MemoryError, match="current=101.0.*peak=102.0"):
        enforce_rss_limit(100)


def test_v6_publication_preserves_existing_v1_through_v5_artifacts(tmp_path: Path) -> None:
    historical = []
    for version in ("v1", "v2", "v3", "v4", "v5"):
        path = tmp_path / f"source_audit_{version}" / "protocol.json"
        path.parent.mkdir()
        path.write_text(json.dumps({"version": version}) + "\n")
        historical.append((path, sha256_file(path)))
    record = {
        "sample_id": "sample-a",
        "split": "train",
        "sequence": "A",
        "rich_geometry_eligible": True,
        "source_coordinates_verified": True,
        "sequence_length": 1,
        "residue_identity_match_fraction": 1.0,
        "complete_local_frame_fraction": 1.0,
        "phi_computable_fraction": 1.0,
        "psi_computable_fraction": 1.0,
        "matrix_valid_pair_count": 0,
        "matrix_rmse_angstrom": 0.0,
        "unexplained_contradiction_count": 0,
        "resolved_exclusion_count": 0,
        "unavailable_reasons": [],
    }
    publish_audit_outputs(
        tmp_path / "source_audit_v6",
        records=[record],
        schema_inventory={},
        protocol={
            "schema_version": AUDIT_SCHEMA_VERSION,
            "storage_estimates": {},
            "phase1_authorization": _authorization([record]),
        },
    )
    assert all(sha256_file(path) == digest for path, digest in historical)
    assert (tmp_path / "source_audit_v6" / "eligibility_manifest.parquet").is_file()


def test_atomic_completed_report_includes_resolved_identifier_exclusion(tmp_path: Path) -> None:
    valid = {
        "sample_id": "valid",
        "split": "train",
        "sequence": "AA",
        "rich_geometry_eligible": True,
        "source_coordinates_verified": True,
        "sequence_length": 2,
        "residue_identity_match_fraction": 1.0,
        "complete_local_frame_fraction": 1.0,
        "phi_computable_fraction": 1.0,
        "psi_computable_fraction": 1.0,
        "matrix_valid_pair_count": 1,
        "matrix_rmse_angstrom": 0.0,
        "unexplained_contradiction_count": 0,
        "resolved_exclusion_count": 0,
        "residue_id_representation": "json_array_string",
        "residue_id_decode_status": "ok",
        "residue_id_duplicate_identifiers": False,
        "insertion_code_representation": "json_array_string",
        "insertion_code_decode_status": "ok",
        "insertion_code_duplicate_identifiers": True,
        "unavailable_reasons": [],
    }
    excluded = {
        **valid,
        "sample_id": "malformed",
        "rich_geometry_eligible": False,
        "eligibility_classification": "excluded_invalid_residue_id_serialization",
        "exclusion_reason": "excluded_invalid_residue_id_serialization",
        "resolved_exclusion_count": 1,
        "residue_id_representation": "malformed",
        "residue_id_decode_status": "malformed",
    }
    output = tmp_path / "source_audit_v6"
    completed = publish_audit_outputs(
        output,
        records=[valid, excluded],
        schema_inventory={"target_identifier_representations": identifier_representation_inventory([valid, excluded])},
        protocol={
            "schema_version": AUDIT_SCHEMA_VERSION,
            "storage_estimates": {},
            "phase1_authorization": _authorization([valid, excluded]),
        },
    )
    assert completed["status"] == "completed"
    coverage = json.loads((output / "coverage_summary.json").read_text())
    counts = coverage["panel_observed_eligibility_counts"]
    assert counts["resolved_exclusion_count"] == 1
    assert counts["exclusion_reason_counts"] == {"excluded_invalid_residue_id_serialization": 1}


def test_configuration_and_storage_estimate_bounds() -> None:
    dedicated = load_yaml("configs/e006_rich_geometry_source_audit.yaml")
    validate_audit_config(dedicated)
    assert dedicated["schema_version"] == AUDIT_SCHEMA_VERSION
    assert dedicated["output_dir"].endswith("source_audit_v6")
    assert CHIRALITY_CONVENTION_VERSION.endswith("_v2")
    assert dedicated["panel_size"] == 512
    config = {
        "panel_size": 512,
        "maximum_selected_structures": 512,
        "maximum_failure_examples": 100,
        "maximum_rss_mib": 2048,
        "phase1_authorization": dedicated["phase1_authorization"],
    }
    validate_audit_config(config)
    config["maximum_rss_mib"] = 2049
    with pytest.raises(ValueError, match="2048"):
        validate_audit_config(config)
    estimates = sidecar_storage_estimates([64, 500], pair_channels=16, residue_channels=32)
    assert estimates[1]["dense_float32_disk_bytes"] == 500 * 500 * 16 * 4
    assert estimates[0]["dense_float16_disk_bytes"] < estimates[0]["dense_float32_disk_bytes"]
    corpus = full_corpus_storage_estimates(
        {"le_64": {"sample_count": 2, "residue_count": 96, "squared_length_sum": 64**2 + 32**2}},
        pair_channels=16,
        residue_channels=32,
        compression_ratio=0.5,
    )
    assert corpus[0]["dense_float32_total_disk_bytes"] == (64**2 + 32**2) * 16 * 4
